# Generated by Django 5.2 on 2025-04-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='autorizacao_uso_imagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='associado',
            name='cep',
            field=models.CharField(default='00000-000', max_length=10),
        ),
        migrations.AddField(
            model_name='associado',
            name='cid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='comprovante_residencia',
            field=models.FileField(blank=True, upload_to='comprovantes/'),
        ),
        migrations.AddField(
            model_name='associado',
            name='data_diagnostico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='data_nascimento',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='associado',
            name='endereco',
            field=models.CharField(default='Endereço não informado', max_length=200),
        ),
        migrations.AddField(
            model_name='associado',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='associado',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='laudo_medico',
            field=models.FileField(blank=True, upload_to='laudos/'),
        ),
        migrations.AddField(
            model_name='associado',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='associado',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='associado',
            name='necessidades_acessibilidade',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='nome_social',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='associado',
            name='numero_associado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='associado',
            name='orgao_emissor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='participa_outros_programas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='recebe_beneficio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='associado',
            name='renda_familiar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='associado',
            name='responsavel_documento',
            field=models.FileField(blank=True, upload_to='responsaveis/'),
        ),
        migrations.AddField(
            model_name='associado',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='associado',
            name='responsavel_parentesco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='associado',
            name='responsavel_rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='status',
            field=models.CharField(default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='termo_adesao',
            field=models.FileField(blank=True, upload_to='termos/'),
        ),
        migrations.AddField(
            model_name='associado',
            name='tipo_deficiencia',
            field=models.CharField(blank=True, default='Não informado', max_length=100),
        ),
    ]
